# Generated by Django 3.2.14 on 2022-07-08 13:57

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', models.CharField(max_length=50, null=True)),
                ('breed_image', cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='image')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BreedGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breed_group', models.CharField(max_length=128, null=True, unique=True)),
                ('description', models.TextField(max_length=2000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BreedReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('review', models.TextField(max_length=200)),
                ('breed_image', cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='image')),
                ('adaptability', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=0)),
                ('friendliness', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=0)),
                ('trainability', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=0)),
                ('health_and_grooming_needs', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=0)),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=0)),
                ('breed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='woofme_app.breed')),
                ('breed_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='woofme_app.breedgroup')),
                ('username', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='breed',
            name='breed_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='woofme_app.breedgroup'),
        ),
    ]
