# Generated by Django 3.2.13 on 2022-05-14 12:04

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('woofme_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='breedreview',
            name='breed_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='breedreview',
            name='breed',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
