# Generated by Django 3.2.14 on 2022-07-08 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('woofme_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='breedgroup',
            name='slug',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
