# Generated by Django 3.2.13 on 2022-05-15 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('woofme_app', '0003_rename_needs_breedreview_health_and_grooming_needs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breedreview',
            name='breed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='woofme_app.breed'),
        ),
    ]
