# Generated by Django 3.2.13 on 2022-05-17 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('woofme_app', '0004_alter_breedreview_breed'),
    ]

    operations = [
        migrations.CreateModel(
            name='BreedGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breed_group', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='breedreview',
            name='slug',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='breed',
            name='group',
            field=models.ManyToManyField(to='woofme_app.BreedGroup'),
        ),
        migrations.AddField(
            model_name='breedreview',
            name='breed_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='woofme_app.breedgroup'),
        ),
    ]
