# Generated by Django 3.2.13 on 2022-05-20 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('woofme_app', '0005_auto_20220517_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breedreview',
            name='published_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
