# Generated by Django 3.2.13 on 2022-05-21 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('woofme_app', '0006_alter_breedreview_published_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breed',
            name='breed_name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
