# Generated by Django 3.2.13 on 2022-05-22 17:53

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('woofme_app', '0007_alter_breed_breed_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breedreview',
            name='breed_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='image'),
        ),
    ]
