# Generated by Django 3.2.13 on 2022-05-23 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('woofme_app', '0008_alter_breedreview_breed_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breedreview',
            name='review',
            field=models.TextField(max_length=200),
        ),
    ]
