# Generated by Django 3.2.13 on 2022-05-25 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('woofme_app', '0009_alter_breedreview_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='breedreview',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
