# Generated by Django 3.2.13 on 2022-05-26 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('woofme_app', '0012_auto_20220526_1510'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='breedgroup',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='breedgroup',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='breedgroup',
            name='description',
            field=models.TextField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='breedgroup',
            name='name',
            field=models.CharField(max_length=128, null=True, unique=True),
        ),
    ]
