# Generated by Django 3.2.13 on 2022-06-26 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('woofme_app', '0014_breedgroup_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='breedgroup',
            old_name='name',
            new_name='breed_group',
        ),
    ]
