# Generated by Django 3.2.13 on 2022-06-27 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('woofme_app', '0016_rename_breed_group_breedgroup_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='breedgroup',
            old_name='name',
            new_name='breed_group',
        ),
    ]
