# Generated by Django 3.2.13 on 2022-06-27 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('woofme_app', '0017_rename_name_breedgroup_breed_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='breedreview',
            name='breed_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='woofme_app.breedgroup'),
        ),
    ]
