# Generated by Django 3.2.13 on 2022-06-27 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('woofme_app', '0018_breedreview_breed_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='breedreview',
            old_name='author',
            new_name='username',
        ),
    ]
