# Generated by Django 3.2.13 on 2022-06-30 19:14

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('woofme_app', '0020_alter_breedreview_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='breedreview',
            name='breed_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='image'),
        ),
    ]
